# Generated by Django 5.2.16 on 2026-07-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text="Slug identifying which app/tool this subscription is for, e.g. 'tracker'.", max_length=50)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('inactive', 'Inactive')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('paddle_subscription_id', models.CharField(blank=True, max_length=100)),
                ('paddle_customer_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product', 'user'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
