# Generated by Django 5.2.16 on 2026-07-22 09:55

from django.db import migrations, models


def hide_liteqa_until_approved(apps, schema_editor):
    Project = apps.get_model("docs", "Project")
    Project.objects.filter(slug="liteqa").update(is_public=False)


def show_liteqa(apps, schema_editor):
    Project = apps.get_model("docs", "Project")
    Project.objects.filter(slug="liteqa").update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_rename_category_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Whether this project is shown in the sidebar and browsable via its project page. Turn off while a project isn't ready to be publicly listed yet — its individual documents stay reachable by direct link regardless, since those are what get shared externally (e.g. submitted to a marketplace listing)."),
        ),
        migrations.RunPython(hide_liteqa_until_approved, show_liteqa),
    ]
