# Generated by Django 5.2.16 on 2026-07-22 10:32

from django.db import migrations, models

LITEQA_DESCRIPTION = """LiteQA is a lightweight test case and test plan management app for **Atlassian Jira Cloud**, hosted on the [Atlassian Marketplace](https://marketplace.atlassian.com/). It adds test case management, execution tracking, traceability, and reporting directly inside Jira — no separate tool to log into.
"""


def set_liteqa_description(apps, schema_editor):
    Project = apps.get_model("docs", "Project")
    Project.objects.filter(slug="liteqa").update(description=LITEQA_DESCRIPTION)


def clear_liteqa_description(apps, schema_editor):
    Project = apps.get_model("docs", "Project")
    Project.objects.filter(slug="liteqa").update(description="")


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_liteqa_public_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text="Markdown supported. Shown at the top of the project's page."),
        ),
        migrations.RunPython(set_liteqa_description, clear_liteqa_description),
    ]
