# Generated by Django 5.2.16 on 2026-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='url_name',
            field=models.CharField(blank=True, help_text="Named URL of the project's own app, if it has one (e.g. 'dashboard'). Shown as an 'Open' link on the project's page. Leave blank for doc-only projects.", max_length=200),
        ),
    ]
