# Generated by Django 5.2.16 on 2026-07-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_seed_expiration_tracker_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
    ]
