# Generated by Django 5.2.16 on 2026-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text="Full URL of the app, if it's hosted on its own separate site (e.g. https://getmenuhub.com/) rather than inside this Django project. Takes priority over url_name for the 'Open' link."),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_name',
            field=models.CharField(blank=True, help_text="Named URL of the project's own app, if it's hosted inside this Django project (e.g. 'dashboard'). Shown as an 'Open' link on the project's page. Leave blank for doc-only projects, or use external_url instead for an app hosted elsewhere.", max_length=200),
        ),
    ]
