# Generated by Django 5.2.16 on 2026-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy'), ('mini_market', 'Mini Market'), ('cafe', 'Cafe'), ('delicatessen', 'Delicatessen'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='notify_phone',
            field=models.CharField(blank=True, help_text='WhatsApp number in E.164 format, e.g. +306912345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('wasted', 'Wasted')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Pieces'), ('kg', 'Kg'), ('liter', 'Liters'), ('box', 'Boxes')], default='piece', max_length=10),
        ),
    ]
