# Generated by Django 5.2.16 on 2026-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('url_name', models.CharField(help_text="Named URL of the tool's entry view, e.g. 'qr_generator:index'.", max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji, e.g. 🔧.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents if not free. Billing integration pending.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
