# Generated by Django 5.2.16 on 2026-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Set automatically when a staff member opens this submission in the admin.'),
        ),
    ]
