# Generated by Django 5.2.16 on 2026-07-24 21:05

import apps.vault.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('item_type', models.CharField(choices=[('api_key', 'API Key'), ('license_key', 'License Key'), ('ssl_certificate', 'SSL Certificate'), ('other', 'Other')], default='api_key', max_length=20, verbose_name='Type')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Vendor / provider')),
                ('secret_value', apps.vault.fields.EncryptedTextField(blank=True, verbose_name='Secret')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('lifetime', 'Lifetime'), ('one_time', 'One-time purchase'), ('none', 'No recurring cost')], default='none', max_length=20, verbose_name='Billing cycle')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('cost_currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Renewal / expiry date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaultProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
