# Generated by Django 5.2.16 on 2026-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultitem',
            name='auto_check_domain',
            field=models.CharField(blank=True, help_text="If set, a daily job checks this domain's real SSL certificate and keeps the renewal date above in sync automatically - e.g. example.com", max_length=255, verbose_name='Auto-check domain (SSL certificates only)'),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='last_check_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
